# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MooseX-Alien
version:      1.00
version_from: lib/MooseX/Alien.pm
installdirs:  site
requires:
    Moose:                         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
